name: Frontend CI

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master, devel ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn install
        working-directory: ./frontend
      - run: yarn build
        working-directory: ./frontend
      - run: yarn lint --max-warnings=0
        working-directory: ./frontend
      - run: yarn test
        working-directory: ./frontend
